---
- name: Deploying IOTGlue-1.14.0
  hosts: localhost
  become: true

  tasks:
    - name: update cache
      apt:
        update_cache: true

    - name: Update disto
      apt:
        upgrade: true
        
    - name: install git
      apt:
        name: git
        state: present
        
    - name: create a folder
      file:
        path: /opt/harsha/
        state: directory
        mode: 777
        
    - name: clone the git repo
      git:
        repo: 'https://github.com/harshabhaskar/terra.git'
        dest: /opt/harsha/terra
